import type { Vacancy } from '@/types/vacancy.types';

export const VacancyFormFields: Record<keyof Vacancy, string> = {
	id: 'id',
	companyName: 'companyName',
	originalDescription: 'originalDescription',
	createdAt: 'createdAt',
	updatedAt: 'updatedAt',
	image: 'image',
	location: 'location',
	jobTitle: 'jobTitle',
	country: 'country',
	salaryMin: 'salaryMin',
	salaryMax: 'salaryMax',
	salaryCurrency: 'salaryCurrency',
	isInferredSalary: 'isInferredSalary',
	isAnnualSalary: 'isAnnualSalary',
	isHourlySalary: 'isHourlySalary',
	isMonthlySalary: 'isMonthlySalary',
	requiredLanguages: 'requiredLanguages',
	requiredRemote: 'requiredRemote',
	seniority: 'seniority',
	employmentType: 'employmentType',
	requiredYearsMin: 'requiredYearsMin',
	requiredYearsMax: 'requiredYearsMax',
	requiredEducation: 'requiredEducation',
	requiredSkills: 'requiredSkills',
	responsibilities: 'responsibilities',
	aiSummary: 'aiSummary',
	contactPerson: 'contactPerson'
};

export const VACANCY_ORIGINAL_DESCRIPTION_MAX_LENGTH = 7000;

export const Currencies = {
	USD: '$',
	EUR: '€',
	GBP: '£',
	JPY: '¥',
	CAD: '$',
	AUD: '$',
	CHF: '₣',
	CNY: '¥',
	HKD: '$',
	RUB: '₽',
	INR: '₹',
	BRL: 'R$',
	ZAR: 'R',
	MXN: '$',
	CZK: 'Kč',
	DKK: 'kr',
	NOK: 'kr',
	SEK: 'kr',
	TRY: '₺',
	GEL: '₾',
	UAH: '₴',
	KZT: '₸',
	KRW: '₩',
	JOD: 'JD',
	KWD: 'KD',
	LYD: 'LD',
	OMR: 'OMR',
	TND: 'TND',
	EGP: 'EGP',
	LBP: 'LBP',
	LRD: 'LRD',
	SLL: 'LRD',
	SYP: 'SYP',
	YER: 'YER',
	XOF: 'CFA',
	XAF: 'CFA',
	XPF: 'CFP',
	VUV: 'VUV',
	WST: 'WS$',
	KMF: 'KMF',
	STN: 'STN',
	SCR: 'SCR',
	SZL: 'SZL',
	TMT: 'TMT'
};
